return {
	synapse = {
		name       = "Synapse X",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	krnl = {
		name       = "KRNL",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	fluxus = {
		name       = "Fluxus",
		writefile  = function(path, data) fluxus.writefile(path, data) end,
		readfile   = function(path) return fluxus.readfile(path) end,
		makefolder = function(path) fluxus.makefolder(path) end,
		isfile     = function(path) return fluxus.isfile(path) end,
		isfolder   = function(path) return fluxus.isfolder(path) end,
		appendfile = function(path, data) fluxus.appendfile(path, data) end,
	},
	delta = {
		name       = "Delta",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	xeno = {
		name       = "Xeno",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	arceus = {
		name       = "Arceus X",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	solara = {
		name       = "Solara",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	wave = {
		name       = "Wave",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	sirhurt = {
		name       = "SirHurt",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	scriptware = {
		name       = "Script-Ware",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	oxygenu = {
		name       = "Oxygen U",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	hydrogen = {
		name       = "Hydrogen",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
	generic = {
		name       = "Unknown",
		writefile  = function(path, data) writefile(path, data) end,
		readfile   = function(path) return readfile(path) end,
		makefolder = function(path) makefolder(path) end,
		isfile     = function(path) return isfile(path) end,
		isfolder   = function(path) return isfolder(path) end,
		appendfile = function(path, data) appendfile(path, data) end,
	},
}
